<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="glspComponentModel" nsURI="http://www.example.org/glspComponentModel"
    nsPrefix="glspComponentModel">
  <eClassifiers xsi:type="ecore:EClass" name="ServerComponent" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="LeafComponent" eSuperTypes="#//ServerComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//ServerComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverComponents" upperBound="-1"
        eType="#//ServerComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramModule" eSuperTypes="#//LeafComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramConfiguration" eSuperTypes="#//LeafComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelTypes" eSuperTypes="#//LeafComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServerLauncher" eSuperTypes="#//LeafComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateNodeHandler" eSuperTypes="#//LeafComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteHandler" eSuperTypes="#//LeafComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="ToolPaletteItemProvider" eSuperTypes="#//LeafComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="SourceModelStorage" eSuperTypes="#//LeafComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="GModelFactory" eSuperTypes="#//LeafComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClientComponent" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EMFSourceModelStorage" eSuperTypes="#//SourceModelStorage"/>
  <eClassifiers xsi:type="ecore:EClass" name="GModelStorage" eSuperTypes="#//SourceModelStorage"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectComponent" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClientModelTypes" eSuperTypes="#//ClientComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateEdgeHandler" eSuperTypes="#//LeafComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeView" eSuperTypes="#//LeafComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="IdGenerator" eSuperTypes="#//LeafComponent"/>
</ecore:EPackage>
